const RESET = 'RESET'
// 项目信息
const PROJECTS = 'PROJECTS'
const PROSELECT = 'PROSELECT'
const PROJECTCHECK = 'PROJECTCHECK'
// 问题信息
const PROBLEMQUEST = 'PROBLEMQUEST'
const PROBLEMLOAD = 'PROBLEMLOAD'
const PROBLEMSELECTID = 'PROBLEMSELECTID'
const PROBLEMDELCONFRIM = 'PROBLEMDELCONFRIM'
const PROBLEMLOADRESET = 'PROBLEMLOADRESET'
const PROBLEMLISTMODEL = 'PROBLEMLISTMODEL'
const PROBLEMDETAILTOSHOW = 'PROBLEMDETAILTOSHOW'
const PROBLEMDETAILRESET = 'PROBLEMDETAILRESET'
// 用户数据
const USERDATAINFO = 'USERDATAINFO'
// 页面数据
const SCREENUPDATE = 'SCREENUPDATE'

export {
  RESET,
  PROJECTS,
  PROSELECT,
  PROJECTCHECK,
  PROBLEMQUEST,
  PROBLEMLOAD,
  PROBLEMSELECTID,
  PROBLEMDELCONFRIM,
  USERDATAINFO,
  PROBLEMLOADRESET,
  PROBLEMLISTMODEL,
  SCREENUPDATE,
  PROBLEMDETAILTOSHOW,
  PROBLEMDETAILRESET
}
